name: Build, Publish and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_publish_job:
    name: Build and Publish Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: |
          npm install

      - name: Build with VuePress
        run: |
          npm run build

      - name: Commit Files
        run: |
          git config --local user.email "guillaume.meyer@outlook.com"
          git config --local user.name "Guillaume Meyer"
          git add .
          git commit -m "publishing" -a

      - name: Push to Published
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: published
          force: true
          
# Disabled as the website is now served by GitHub Pages

# deploy_job:

#   name: Deploy Job
#   needs: build_publish_job
#   runs-on: ubuntu-latest

#   steps:
#     - name: Checkout Published
#       uses: actions/checkout@v2
#       with:
#         submodules: true
#         ref: published

#     - name: Deploy to Azure
#       uses: Azure/static-web-apps-deploy@v1
#       with:
#         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_0D8A0C510 }}
#         repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
#         action: "upload"
#         # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
#         app_location: "/dist" # App source code path
#         api_location: "" # Api source code path - optional
#         output_location: "" # Built app content directory - optional
